baseURL: ''
title: Elektronica
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

params:
  author: Pranjal Prajapati
  moto: "The platform for students to dream innovative practical projects and achieve them."
  description: "The Electronics and Signals club of IIT Hyderabad is a student organization that aims to increase student interest in electronics. The Club was founded in 2009, and it has come a long way since then."
  disable_theme_toggle: false

  p1:
    heading: "Our mission"
    image: "images/pages/our-mission.jpg"
    content:
      - text: "Philosophy: \"Learning by doing\" — Whether you're building, debugging, designing, or researching, there's a place for you here."
      - text: " "

  p4:
    heading: "Explore Electronics and Signal Processing"
    content:
      - text: "Find the most insightful blogs on various topics here."

  social_media:
    github:
      enabled: true
      url: 'https://github.com/orgs/Elektronica-IITH/repositories'
    instagram:
      enabled: true
      url: 'https://www.instagram.com/elektronica_iith'
    twitter:
      enabled: true
      url: 'https://x.com/xElektronica'

  TeamMembers:
  - name: "Annapureddy Sai Ramyasri"
    photo: "/images/team/Annapureddy Sai Ramyasri.jpg"
  - name: "Anoop K"
    photo: "/images/team/Anoop K.jpg"
  - name: "Ashok"
    photo: "/images/team/Ashok.png"
  - name: "Bhavanisankar G S"
    photo: "/images/team/Bhavanisankar G S.webp"
  - name: "Byla Sanjith"
    photo: "/images/team/Byla Sanjith.jpg"
  - name: "Devi Amrutha"
    photo: "/images/team/Devi Amrutha.jpg"
  - name: "John Bobby"
    photo: "/images/team/John Bobby.jpg"
  - name: "K.Akhil"
    photo: "/images/team/K.Akhil.jpg"
  - name: "Krishna Patil"
    photo: "/images/team/Krishna Patil.jpg"
  - name: "Lakshitha Totakura"
    photo: "/images/team/Lakshitha Totakura.jpg"
  - name: "Nithin Surya S"
    photo: "/images/team/Nithin Surya S.png"
  - name: "Pilli Sri Naga Madhukar"
    photo: "/images/team/Pilli Sri Naga Madhukar.jpg"
  - name: "Priyanshu"
    photo: "/images/team/Priyanshu.jpg"
  - name: "Rishikesh"
    photo: "/images/team/Rishikesh.jpg"
  - name: "Ritam Basu"
    photo: "/images/team/Ritam Basu.jpeg"
  - name: "Riva Mohta"
    photo: "/images/team/Riva Mohta.jpg"
  - name: "Sarthak Kumar Mishra"
    photo: "/images/team/Sarthak Kumar Mishra.png"
  - name: "Sidharth V"
    photo: "/images/team/Sidharth V.jpg"
  - name: "Y. Harsha Vardhan Reddy"
    photo: "/images/team/Y. Harsha Vardhan Reddy.jpg"
  - name: "J.KEDARANANDA"
    photo: "/images/team/J.KEDARANANDA.webp"
  - name: "Soham Prabhakar More"
    photo: "/images/team/Soham Prabhakar More.png"
  - name: "Mihir Divyansh"
    photo: "/images/team/Mihir Divyansh.png"
    

menu:
  main:
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 20
    - identifier: team
      name: Team
      url: /team/
      weight: 30
    # - identifier: contact
    #   name: Contact
    #   url: /contact/
    #   weight: 50
  footer:
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 10
    - identifier: team
      name: Team
      url: /team/
      weight: 30
    # - identifier: contact
    #   name: Contact
    #   url: /contact/
    #   weight: 50

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

module:
  hugoVersion:
    extended: true
    min: "0.114.0"